---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "UpgradeFrom0_7_1"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "atomist-rugs/rug-upgrade"
    branch: "master"
    sha: "e556ba9*"

---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "UpgradeFrom0_7_1"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "atomist-rugs/rug-upgrade"
    branch: "master"
    sha: "e556ba9*"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "AddTypeScriptGenerator"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.13.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors"
    branch: "allow-non-ts-projects"
    sha: "82096c8*"
  parameters:
    - "generator_name": "StaticPage"
    - "description": "A new Elm project, simplest possible"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "UpdateRug"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0-20170524133032"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "894b141b3e1662c99b5ad5d50431389ddb6cddd2"
    sha: "894b141"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0-20170524133032"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "894b141b3e1662c99b5ad5d50431389ddb6cddd2"
    sha: "894b141"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "AddTypeScriptEditor"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0-20170524133032"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "894b141b3e1662c99b5ad5d50431389ddb6cddd2"
    sha: "894b141"
  parameters:
    - "editorName": "UpgradeToBeginnerProgram"
    - "description": "Turn a static page into an interactive page"

<<<<<<< HEAD
=======
---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "AddTypeScriptEditor"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0-20170524133032"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "894b141b3e1662c99b5ad5d50431389ddb6cddd2"
    sha: "894b141"
  parameters:
    - "editorName": "FeatureToSteps"
    - "description": "generate the steps for our features"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "019498b*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "019498b*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "019498b*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "b7ea2d6*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "b7ea2d6*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "18181c0*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "1d4a121*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "a95bae2*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "c95dcc8"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "85417f5*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "85417f5*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "85417f5*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "85417f5*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "85417f5*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "85417f5*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "85417f5*"
  parameters:
    - "featureFile": ".atomist/tests/project/FeatureToStepsTest"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "FeatureToSteps"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "3.0.0"
  origin:
    repo: "git@github.com:jessitron/elm-rugs"
    branch: "feature-to-steps"
    sha: "c787787*"
  parameters:
    - "featureFile": ".atomist/tests/project/UpgradeToBeginnerProgramTest"

<<<<<<< HEAD
>>>>>>> bcf0506... treat same level as a move left
=======
---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "AddTypeScriptEditor"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0-20170530183725"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "15a7feb96bfe7aa261790e8b7fa3d79b79014c3b"
    sha: "15a7feb"
  parameters:
    - "editorName": "ChangeMain"
    - "description": "Change the body of the main function"

>>>>>>> 720347f... Adds a TypeScript Rug editor to a Rug project
