---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "UpgradeFrom0_7_1"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "atomist-rugs/rug-upgrade"
    branch: "master"
    sha: "e556ba9*"

---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "UpgradeFrom0_7_1"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "atomist-rugs/rug-upgrade"
    branch: "master"
    sha: "e556ba9*"

---
kind: "operation"
client: "rug-cli 0.24.0"
editor:
  name: "AddTypeScriptGenerator"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.13.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors"
    branch: "allow-non-ts-projects"
    sha: "82096c8*"
  parameters:
    - "generator_name": "StaticPage"
    - "description": "A new Elm project, simplest possible"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "UpdateRug"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0-20170524133032"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "894b141b3e1662c99b5ad5d50431389ddb6cddd2"
    sha: "894b141"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0-20170524133032"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "894b141b3e1662c99b5ad5d50431389ddb6cddd2"
    sha: "894b141"

